language: cpp
sudo: required
install: sudo apt-get install cmake

script: sudo apt-get install software-properties-common && yes '' | sudo add-apt-repository ppa:george-edison55/cmake-3.x && sudo apt-get update && sudo apt-get install cmake -y && mkdir build && cd build  &&  cmake ../ && make
